### ISSUE TITLE
Feedback netkaart s1279 - 20kV -> 10kV

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#1028]
Naam : Jeffrey Kog (jk-5)<br/>Email : _Bekend bij de redactie_<br/>ID : [s1279](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=s1279)<br/>Feedback tekst :<br/>====================<br/>Klein stukje detail, hier is alleen 10kV aanwezig, geen 20kV. Beschrijving mag dus worden aangepast van 20kV naar 10kV.<br/>====================

**Comment by HansNien** [comment]
Dank, moet een typo zijn geweest. Rest van de beschrijving plus het label ging netjes uit van 10 kV, behalve het getalletje. Er zal wel een cijfer naast de 1 zijn aangetikt op een toetsenbord.
