### ISSUE TITLE
Energiepark Pottendijk Nieuw-Weerdinge 

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#1032]
Naam : Arthur Kamminga <br/>Email : _Bekend bij de redactie_<br/>ID : [n.v.t.](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=n.v.t.)<br/>Feedback tekst :<br/>====================<br/>Energiepark Pottendijk bij Nieuw-Weerdinge staat nog niet op de kaart. Aanleg aansluiting op station Weerdinge is in aanleg, park zelf nog niet. Betreft zonnepark en windpark van Shell: https://www.shell.nl/energy-and-innovation/energiepark-pottendijk.html
Kabeltracé naar Weerdinge: https://www.enexis.nl/storingen-en-onderhoud/werkzaamheden/drenthe/nieuwe-weerdinge-uitbreiding-elektriciteitsnet-windmolenpark-pottendijk
<br/>====================

**Comment by HansNien** [comment]
Duurde even, want er liepen wat rechtszaken en het intekenen van bepaalde objecten die nog niet onherroepelijk zijn levert soms wat eh.. minder plezierige mail op. Het gebied in kwestie kent vrij veel temperament als het gaat om windmolens en alles wat er bij die discussie komt kijken. We hebben de kabels en het zonnepark (in beraming) ingetekend, maar met de windmolens wachten we om bovengenoemde reden totdat de fundamenten er ook echt liggen. Intussen, uiteraard, dank!
