### ISSUE TITLE
Feedback netkaart; voormalige mast 50 kV Hoorn - Enkhuizen

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#109]
Naam : anoniem<br>Email : anoniem@hotmail.com<br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID="></a><br><br>Feedback tekst : <br>Op de positie 52,659044 , 5,094719 (achter de brandweer in Hoorn Blokker)staat een telecommast die veel weg heeft van een 50 kV hoogspanningsmast. Deze staat precies op een opstijgpunt van de voormalige 50 kV verbinding Hoorn Enkhuizen. Deze verbinding is in 2001 gesloopt nadat er reeds jaren grotere tracés in Hoorn en Enkhuizen verkabeld waren.<br />
<br />
Is overigens nog goed terug te vinden op topotijdreis.nl<br />
<br />

**Comment by BaDu-HSN** [comment]
Dank voor uw feedback.
We gaan er mee aan de slag.

**Comment by HansNien** [comment]
De mastpostitie is toegevoegd als spanningsloos op de netkaart, met bijbehorende informatie.
