### ISSUE TITLE
Ingekomen via de mail, issue 70 kV Wielsbeke

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Netkaart#110]
Bericht:
Beste
Ik heb een kleine fout of onnauwkeurigheid ontdekt in jullie kmz file 6.0.  De door jullie ingetekende hoogspanningslijn komt niet overeen met de realiteit dit  thv Wielsbeke in de Reynaertstraat  (zie bijlage)

ps jullie tool is zeer handig en gebruiksvriendelijk

mvg

Het betreft een gemiste bocht in een 70 kV verbinding in Wielsbeke. Edit HN 08jan18: bijlage toegevoegd zoals die aan de email vastzat.

![wielsbeke](https://user-images.githubusercontent.com/23345566/34690597-0a93782e-f4ba-11e7-95dd-48cb1fef3731.jpg)

**Comment by coreice** [comment]
Even kortsluiten met Johan omdat deze ook bezig is in Vlaanderen.

**Comment by HansNien** [comment]
Wel aardig omslachtig. Ik gok er stiekem even op dat Johan niet alle tracés aanpast en heb het zojuist in orde gemaakt. Mocht blijken dat een import van Johan hem weer met het oude onjuiste tracé overschrijft, dan pas ik hem een tweede keer aan.
