### ISSUE TITLE
Aansluiting Windnet Bergen op Zoom

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#1107]
Naam : anoniem<br/>Email : _Bekend bij de redactie_<br/>ID : [s1184](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=s1184)<br/>Feedback tekst :<br/>====================<br/>Dit is een 33/10 kV transformator, geen 150 kV transformator. Windnet is aangesloten op het net van Enexis volgens de ACM. Deze transformator stond er al in 2008/2009 (drie jaar voordat het 150 kV veld gebouwd werd) en is niet ook niet veranderd in de jaren daarna (zie topotijdreis luchtfoto's of google streetview). Dit is dus geen 150/33 kV trafo en moet dus een 10/33 kV trafo zijn. Zie ook https://www.acm.nl/download/documenten/acm-energie/overzicht-lopende-en-afgeronde-ontheffingaanvragen-oktober-2014.xlsx

Rond 2010/2011 is er wel iets (trafobox?) gebouwd net ten zuiden van station Bergen op Zoom gelijktijdig met het 150 kV veld, maar dit is in 2012 weer gesloopt. Op deze locatie lijken ook haspels met rode MS kabels te hebben gestaan (zie topotijdreis). Het 150 kV veld heeft echter nog stees geen eindsluitingen. Ze hadden wel ooit een plan om naar 150 kV te gaan https://zoek.officielebekendmakingen.nl/stcrt-2013-11982.pdf Het lijkt er op alsof Windnet hun 150 kV aansluiting toch 2 voor 12 niet rond kreeg, terwijl werkzaamheden al gestart waren. Inmiddels lijkt het er op dat TenneT dit veld gaat gebruiken voor de kabel richting Woensdrecht, dus dat het 150 kV plan van Windnet definitief niet door gaat.<br/>====================

**Comment by HansNien** [comment]
Daar zat wat uitvlooiwerk onder, maar inmiddels is dit inderdaad te bevestigen vanuit opendata van netbeheerder Enexis (10 kV). Een wonderlijke situatie en hartelijk dank voor het uitzoeken en de moeite om het aan ons te melden. We hebben het aangepast op de kaart.
