### ISSUE TITLE
Masten 29 tm 113 van Bressoux-Battice-PtRechain (926-916) in 2018 buitendienst

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Netkaart#137]
Evt ook eerst wit zetten

**Comment by HansNien** [comment]
Dat zijn die 70 kV-verbindingen die ze eraf gaan schuiven volgens Shrek. Iemand heeft 'm al netjes op wit gezet, maar de masten nog niet. Kleine moeite, maar grote denkstap. Ze komen nu als spanningsloos in de database te staan en zullen in een eventuele historische weergave altijd als spanningsloos getoond worden: zodra die feature een keer aan de loop is moeten we ze dus terug aanpassen.

**Comment by BavoLens** [comment]
Intussen zijn de masten gesloopt, kunnen ze weer op 70kV met sloopdatum 2018 gezet worden?

**Comment by Netkaart-feedback** [comment]
121 masten op sloop=2018 gezet (en spanning op 0)

**Comment by Netkaart-feedback** [comment]
Dat was te veel denk ik, ik heb alles weer op 70kV gezet en sloop 9999.
De mast nummering is lastig op te filteren aangezien er soms een puntje (.) aan het eind staat.
Dat maakt het creeren van een goeie query erg lastig.
