### ISSUE TITLE
Feedback netkaart Haarlem 50kv

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#138]
Naam : tender<br>Email : Bekend bij de redactie <br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID="></a><br><br>Feedback tekst : <br>resultaat onderzoek locatiegegevens 50kv centrum Haarlem.<br />
zoek op google naar de combinatie van de volgende trefwoorden: tenderned kenaupark 50kv 16.200

**Comment by HansNien** [comment]
Dank voor de feedback, zojuist is deze verwerkt. 
Helaas ontbreekt er in de intekening een klein stukje kabel op een onlogische plek. Men zou daar normaal gesproken een verknoping of station verwachten, maar omdat we geen informatie hebben van die plek (er is ons daar geen station bekend) is de bestaande kabel daar maar gewoon doorgelast met een krulletje. (De andere hoefijzervormige lus is een feature die we wel vaker zien in grondkabels, die staat niet ter discussie.)

**Comment by Knarvel** [comment]
Veldwerk ter plaatse leert dat hier alleen gras en stoeptegels te vinden zijn, geen kast of station.
De diagonale kabel op blad 1  zou ook een aparte (opgegeven?) kabel van/naar Haarlem-Noord of het voormalige station Oudeweg kunnen zijn.
