### ISSUE TITLE
Deelnetten België 150kV

### ISSUE THREAD

**Issue by BavoLens** [Hoogspanningsnet/Netkaart#139]
Ik zag dat er bij sommige 150kV-lijnen in België een deelnet "Antwerpen" staat. 
In de netten >36kV zijn er geen deelnetten, kan dit veld voor alle lijnen van 70,150,220 en 380 kV in België leeggemaakt worden?

**Comment by HansNien** [comment]
Goed punt.
In het concept voor versie 7 (nieuwe netkaartbijbelversie met verwerking van de inzichten van de vergadering is onder constructie) worden niet-ingevulde velden bijna standaard verborgen, maar het veld 'deelnet' is natuurlijk wel ingevuld al is het dan niet correct in België. Met de huidige architectuur is dat niet op te lossen als we ze in Nederland wel willen behouden, wat overigens m.i. geen uitgemaakte zaak is. Voor België heb je echter volledig gelijk. 
Ik denk dat we dit aan Bas of Mark moeten vragen, dit vergt wat custom code om het veld in België leeg te forceren met een query op de achtergrond ofzo. Deze vraag kan ook beter worden verplaatst naar de developers-hub (alleen hoe doe je dat).

**Comment by BavoLens** [comment]
In bestaande lijnen kan ik perfect handmatig het veld deelnet leegmaken zonder dat er errors of dergelijke zijn. Volgens mij moet het dus gewoon kunnen om voor alle lijnen in België met spanning 70kV of meer het veld deelnet leeg te maken.

**Comment by HansNien** [comment]
Dat is mooi, maar doe nog even rustig aan met daar tijd in te stoppen. 
Juist een paar dagen terug is er in de netkaartdevelopers-appgroep (als je erbij wil, dat kan) een discussie ontstaan over deelnetten en hun steeds verder wankelende positie in het netkaartframework. Mogelijk verlaten we het hele concept van deelnetten zelfs, zodat dan op een automatische manier dat gehele veld overal komt te vervallen. Er is nog niets definitief besloten, maar het lijkt erop dat de neuzen ongeveer allemaal die richting op staan.

**Comment by HansNien** [comment]
Een paar jaar en een paar vergaderingen verder... In V7 worden deelnetten een arbitrair veld dat kan worden ingevuld, maar uit de mappenboom vervalt. Daarmee is dit item opgelost vanaf de release van de nieuwe versie.
