### ISSUE TITLE
Feedback netkaart m12611 (begin verbinding utrecht - soest)

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#143]
Naam : Koos van den Hout<br>Email : Bij de redactie bekend<br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID=m12611">m12611</a><br><br>Feedback tekst : <br>Ik heb een foto gemaakt van deze mast in 2007 (ook al weer 11 jaar geleden), deze is onder een cc-by-sa beschikbaar via https://www.flickr.com/photos/8101127@N06/481221502/in/dateposted-public/<br />

**Comment by KHoos** [comment]
Jammer dat jullie het opgegeven e-mail adres ook gelijk op github zetten, ik ging er even van uit dat een site zoals die van jullie geen datalek zou zijn. Ik wil dat zo snel mogelijk verwijderd hebben (dat veranderd niets aan het aanbod van de foto)

**Comment by BaDu-HSN** [comment]
Hoi Koos,

Dit is ons ook een doorn in het oog, je adrtes is inmiddels verwijdert.
Bedankt voor je bijdrage.

**Comment by HansNien** [comment]
Beste heer Van den Hout,

Dank voor uw bericht. Helaas maken we geen gebruik van los ingestuurde foto's.
We gebruiken alleen foto's die op ons forum zijn gehost en die zijn geplaatst door mensen met een account (gekende fotografen bij ons) of van foto's die zich in het public domain bevinden. We doen dit om kwesties rond auteursrecht te vermijden en omdat losse toestemmingen (hoe vriendelijk ook) moeilijk rechtsgeldig bewijsbaar zijn als het erop aankomt. Soms jammer, maar het is hoe de wereld van nu in elkaar zit.
