### ISSUE TITLE
Feedback netkaart s5690 - 20kV in Emmeloord

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#1719]
Naam : Jeffrey Kog<br/>Email : _Bekend bij de redactie_<br/>ID : [s5690](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=s5690)<br/>Feedback tekst :<br/>====================<br/>Station Emmeloord Zuidervaart heeft tegenwoordig ook een actieve 20kV stap, na aanleg van twee nieuwe trafovelden op 110kV. Op de recentste foto op de Hoogspanningskaart is al te zien dat er 2 extra trafo's zijn gebouwd.

Er is inmiddels een 20kV circuit aangelegd naar Urk, waar een nieuw regelstation 'Urk-Zuid' de spanning omlaag brengt naar 10kV voor de directe omgeving van Urk. Hetzelfde gaat gebeuren naar Tollebeek.

Zie de tekening op deze site: https://www.liander.nl/urk<br/>====================

**Comment by HansNien** [comment]
Dank, was even een bevalling, maar we hebben deze verwerkt op de netkaart. De 10 kV kabels laten we nog even achterwege, mogelijk wordt dat een keer het domein van opendata zonder eigen inbreng.
