### ISSUE TITLE
Feedback netkaart Umspannwerk Michelbach

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#1743]
Naam : (naam bekend bij redactie) <br/>Email : _Bekend bij de redactie_<br/>ID : [n.v.t.](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=n.v.t.)<br/>Feedback tekst :<br/>====================<br/>Met veel interesse volg ik uw werk (site, forum en kaart) al jaren. Zelfs onze nieuwe Heimat staat op de kaart. Vlak bij ons is sinds dit voorjaar een nieuw trafostation 110/20 kV met de naam Michelbach in gebruik genomen tussen Marburg-Süd en Lahntal. U vindt de locatie op openstreetmap.org ca. 400 noordelijk van de rotonde L3092/K77, coördinaten 50.8427,8.6925. Zie ook https://www.eam.de/ueber-uns/pressemitteilung/die-eam-startet-mit-dem-bau-des-neuen-umspannwerks-michelbach/ Desgewenst kan ik u foto's sturen. Veel groeten uit Marburg <br/>====================

**Comment by Knarvel** [comment]
Het station is op de kaart ingevoerd, dank u voor de tip!
Fotoos zijn altijd welkom, maar om copyright-redenen gebruiken wij alleen fotoos van forumsleden die door hen op persoonlijke titel op het forum gepubliceerd zijn. De rauwe internet realiteit maakt dit helaas nodig.
