### ISSUE TITLE
Feedback netkaart v25019 110 kV Heekstraat - Vechtstraat (2)

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#1752]
Naam : Andre van Berkel<br/>Email : _Bekend bij de redactie_<br/>ID : [v25019](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=v25019)<br/>Feedback tekst :<br/>====================<br/>Hallo,

Kabel 	110 kV Heekstraat - Vechtstraat (2) Enschede lijkt voorlopig nog niet aangelegd en dus ook niet in bedrijf: https://www.tennet.eu/nl/projecten/nieuwe-110kv-hoogspanningskabel-enschede <br/>====================

**Comment by HansNien** [comment]
Even nagekeken, en dat klopt. Zelden duurt het zo lang om zo'n kort kabeltje aan te leggen. We hebben de nieuwe kabel even 'on hold' gezet en van de kaart geplukt, de oude moet het nu weer doen. Dank voor het scherpe oog.
