### ISSUE TITLE
ondergrondse kabels

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#180]
Naam : perik<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID=m11920">m11920</a><br><br>Feedback tekst : <br>hebben jullie ook een kaart waarop de ondergronds hoogspanningskabels liggen?

**Comment by BaDu-HSN** [comment]
Onze webkaart geeft de ons bekende hoogspanningsverbindingen (ondergronds en bovengronds) weer.
Aan de kleur kunt u zien of het om een kabel (ondergronds) of een hoogspanningslijn (bovengronds) gaat. Bijvoorbeeld voor 150kV is een bovengrondseverbinding donkerblauw en een ondergrondse lichtblauw (cyaan). 
In de legenda van de webkaart (klik op het icoontje met de drie horitzontale streepjes) krijgt u de betekenis van de kleuren te zien.

![image](https://user-images.githubusercontent.com/21307438/39958192-f91cdbf6-55ff-11e8-9eb5-77b3b24974b6.png)
