### ISSUE TITLE
Nieuw 150 kV station Lelystad Larserringweg

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#1803]
Naam : Jan<br/>Email : _Bekend bij de redactie_<br/>ID : [m12729](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=m12729)<br/>Feedback tekst :<br/>====================<br/>Zie hier voor toekomstige locatie en kabels

https://www.ruimtelijkeplannen.nl/documents/NL.IMRO.0995.BP00099-OW01/t_NL.IMRO.0995.BP00099-OW01.html#_1.2_Achtergrondendoel<br/>====================

**Comment by HansNien** [comment]
Dank, we hebben beide terreinen op de kaart toegevoegd. De kabels kunnen we nu nog niks mee beginnen op de kaart, die moeten eerst fysiek gelegd worden voor we ze als spanningsloos (in aanleg) kunnen weergeven. We houden het in de gaten.
