### ISSUE TITLE
Kleur knooppunt Zandvoorde

### ISSUE THREAD

**Issue by BavoLens** [Hoogspanningsnet/Netkaart#183]
In Zandvoorde is een nieuw opstijgpunt gebouwd. Hoewel het om een 36kV-lijn gaat heeft het toch verkeerdelijk de blauwe kleur gekregen.

**Comment by BavoLens** [comment]
Het probleem doet zich enkel voor in google earth, op de webkaart heeft hij wel de juiste kleur

**Comment by BaDu-HSN** [comment]
OK. duidelijk een verschilletje in de kleuren xml.
Ik ga op onderzoek uit

**Comment by BaDu-HSN** [comment]
Fixed

**Comment by BavoLens** [comment]
Nou niet echt, nu zijn in google earth alle knooppunten verdwenen

**Comment by BaDu-HSN** [comment]
Damn, das weer minder
FF uitzoeken

**Comment by BaDu-HSN** [comment]
Nu als het goed is wel gefixed, kijk voor de zekerheid even.

**Comment by BavoLens** [comment]
Ja nu is het goed, bedankt !
