### ISSUE TITLE
Laden volledige netkaart stoek...

### ISSUE THREAD

**Issue by Knarvel** [Hoogspanningsnet/Netkaart#186]
![afbeelding](https://user-images.githubusercontent.com/22664015/41005616-927bb8a4-691e-11e8-80be-5dd3326640f9.png)

De download voor de volledige netkaart werkt niet, in plaats daarvan krijg ik een piepklein kml bestandje dat bovendien niet wil laden vanwege een https fout  of zoiets...  :-(

**Comment by BaDu-HSN** [comment]
de beheerpagina gebruikt tegenwoordig ook https, dus de juiste URL is:
https://netkaart.hoogspanningsnet.com/beheer/beheer.php

Als je deze gebruikt werkt de download prima
