### ISSUE TITLE
Opmerking op netkaart - t3484

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Netkaart#188]
Arie via het forum:
_bij het kijken naar het aansluiten van wind op zee in duitsland
zag ik een station met de verkeerde naam
bij het station bij Emden (t3484) staat Emden Ost maar hij heet Emden Borssum
bij het nieuwe station (t3996) Emden Ost staat geen naam (deze heet wel Emden Ost)_

**Comment by HansNien** [comment]
Dank voor de melding. Het is zojuist direct aangepast, hoewel er op een later moment nog wel even research moet worden gedaan naar hoe dat nieuwe station met de converter eigenlijk in het bestaande net hangt en wat voor spanningen er gevoerd worden. Ook de geografische afwerking kan eventueel nog wat verbeterd worden. Ik zet 'm daarom nog niet helemaal op opgelost, maar op work in progress.

**Comment by HansNien** [comment]
Zojuist even opnieuw bekeken met de nieuwe luchtfoto's erbij. Als het goed is voldoet ie nu wel weer even.
