### ISSUE TITLE
Locatie voormalig 50/10 kV onderstation Zevenaar

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#201]
Naam : anoniem<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID="></a><br><br>Feedback tekst : <br>Op de locatie doesburgseweg 16 in Zevenaar was vroeger het 50/10 kV onderstation Zevenaar gevestigd. Dit heeft niet lang bestaan (1970 - 1980) volgens Topotijdreis.<br />
<br />
Gebouw lijkt nog origineel. Trafoboxen zijn verbouwd voor opslag of andere functionaliteiten

**Comment by HansNien** [comment]
Dank voor de aanvulling.
Waarschijnlijk kunnen we hem al wel intekenen, maar in deze plaats hebben we de luxe dat er een cartograaf woont. Die hebben we gevraagd eens even een blik te werpen om in te schatten of het redelijkerwijs nog herkenbaar is als ex-station. Waarschijnlijk verschijnt het station binnenkort als spanningsloos op de netkaart.

**Comment by HansNien** [comment]
Inmiddels op de kaart gezet, met toelichting.
