### ISSUE TITLE
Zie niet alle netten.

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#2141]
Naam : Jan MICHIELS<br/>Email : _Bekend bij de redactie_<br/>ID : [n.v.t.](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=n.v.t.)<br/>Feedback tekst :<br/>====================<br/>Zie geen 10kV netten en of middenspannings lijnen.

Bijvoorbeeld Lammerdries Olen.
Zie ik enkel de rode HS lijn van 363-420kV.

Hoe kan meer zien ? 
Ben al volledig ingezoomd.<br/>====================

**Comment by BavoLens** [comment]
De scope van de kaart in België is beperkt tot het hoogspanningsnet, het laag- en middenspanning komt er dus niet op voor.
