### ISSUE TITLE
Afkorting station Goor verkeerd

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#2150]
Naam : Anoniem<br/>Email : _Bekend bij de redactie_<br/>ID : [s1256](https://netkaart.hoogspanningsnet.com/balloon3.php?ID=s1256)<br/>Feedback tekst :<br/>====================<br/>In de hoogspannigskaart staat dat de afkorting van station Goor GR is, volgensmij moet dat GR zijn. GR110 is de afkorting vziw<br/>====================

**Comment by Knarvel** [comment]
Afko bijgewerkt, dank u.
