### ISSUE TITLE
Feedback - Nieuwe verbindingen Tilburg

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#223]
Naam : Coen<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID="></a><br><br>Feedback tekst : <br>Beste,<br />
<br />
Op dit moment is 150kV station Tilburg West aangepast waarbij de lijn volledig het station in gaan. Er dus geen doorlussing meer tussen mast 141 en 142.<br />
Daarnaast is er ook een nieuwe kabel verbinding gerealiseerd tussen Tilburg West en Tilburg Zuid.

**Comment by HansNien** [comment]
Hartelijk dank, deze hebben we direct verwerkt op de netkaart. 
Het was bekend dat er hier een nieuwe kabel zou worden gelegd en dat er wat nieuwe velden op de stations nodig zouden zijn, maar dat die nu al klaar is was ons even ontgaan. Grafisch klopt het nu weer, nu de capaciteiten en circuitkleuren nog boven water krijgen.
