### ISSUE TITLE
Enduris gebied aanvullingen

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#230]
Naam : anoniem<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID="></a><br><br>Feedback tekst : <br>Beste Hoogspanningsnet. <br />
<br />
De aansluiting Thermphos in Vlissingen wordt in het KCD van Enduris 150 kV station Sloe genoemd. Een 150/30 kV station wat enkele grote gebruikers heeft. Adres volgens KCD is Europaweg Zuid 4 te Rithem. Mogelijk zijn dus beide circuits van de 150 kV lijn richting Thermphos nog in bedrijf. Staat overigens ook in het KCD dat AES Energy Storage aangesloten is op dit station. Dus die 30 kV verbinding richting Borssele of de Sloe eigen bedrijf staat mogelijk niet goed.<br />
<br />
Daarnaast staan in het KCD nog 2 overgangsstations 50 kV. Stations waar je overgaat van een land naar een zee-kabel. Die zijn volgens mij al uit bedrijf. Maar een ervan (Eendagtpolder) is hier te vinden:<br />
https://www.google.nl/maps/@51.3625806,3.9317088,3a,75y,169.11h,82.94t/data=!3m6!1e1!3m4!1s71pFd4ciG0c8lODXqJ5Atg!2e0!7i13312!8i6656<br />
De andere (Bakendorp) https://www.google.nl/maps/@51.3998573,3.9027591,3a,37.5y,250.28h,91.61t/data=!3m6!1e1!3m4!1sOOs_xXS9oPDbaTPXahcXBA!2e0!7i13312!8i6656 <br />

**Comment by HansNien** [comment]
Dank voor de aandraging.
Er zat inderdaad nog wat achterstallig werk in Borssele. Inmiddels is de zaak daar onder handen genomen en weer in orde.
