### ISSUE TITLE
Utrecht 50 kV Lageweide - Utrecht - Zuid en Merwedekanaal - Overvecht

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#231]
Naam : anoniem<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID="></a><br><br>Feedback tekst : <br>Beste hoogspanningsnet. Recent fietst ik door Utrecht en zag ik de welbekende zwarte hoogspanningskabels opgehaspeld liggen.<br />
<br />
Het bleek om de aanleg/vervanging te gaan van een 50 kV kabel Lage Weide - Utrecht Zuid. Kabel loopt vanaf de Everard Meijsterlaan parallel aan de Mozartlaan richting de Bartoklaan (allen Utrecht). De 50 kV kabel Lage Weide - Utrecht Zuid staat op een andere plek ingetekend in jullie kaart. Ook in de Everard Meijsterlaan tot de Lessinglaan zag ik werkzaamheden.De kabel wordt overigens wel verzwaard, dus allicht dat dit het geval is.<br />
<br />
Zie hier de vergunning<br />
https://zoek.officielebekendmakingen.nl/wsb-2018-10681.html <br />
<br />
Het bedrijf wat deze kabel aangelegd heeft (en de kabels richting Overvecht is hier redelijk helder over) en geeft het complete tracé. Ook het eerste stukje Merwedekanaal - Overvecht staat hier tot in detail op wat natuurlijk een goede aanvulling is.<br />
<br />
https://www.ageladviseurs.nl/aanleg-nieuwe-50-kv-verbinding-utrecht-overvecht-lage-weide/<br />
<br />
<br />
<br />

**Comment by HansNien** [comment]
Op een klein open vraagje na (het kabelaantal komt niet overeen, mogelijk wordt een enkelvoudige oude kabel vervangen door een dubbele nieuwe) is de situatie nu aangepast. Dank.
