### ISSUE TITLE
Amersfoort2

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#232]
Naam : Geen<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID="></a><br><br>Feedback tekst : <br>Beste hoogspanningsnet. Rondstation Amersfoort 2 is gewerkt. De transformatoren zijn/worden rechtstreeks aangesloten op de kabels vanaf Soest2. De kabels vanaf Amersfoort2 naar Amersfoort3 en Amersfoort1 zijn doorgelust op elkaar. Amersfoort 1 en Amersfoort 3 hebben dus nu een rechtstreekse verbinding.<br />
<br />
https://vangelder.com/projecten/ombouw-schakelstation-amersfoort-2/<br />
<br />
<br />
<br />
<br />

**Comment by HansNien** [comment]
Bedankt, deze is zonder problemen verwerkt. Nieuwe trafo's op steeltjes dus.
