### ISSUE TITLE
vraag zuid-limburg

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#242]
Naam : Mark Rurup<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID="></a><br><br>Feedback tekst : <br>Hallo, kunt u ook achterhalen hoe de kaart er in het verleden uit heeft gezien? Wij hebben vragen over een specifiek perceel waar nog zakelijk recht op rust m.b.t. hoogspanningsmasten en -kabels. In de huidige situatie zijn die er niet, zo lijkt het. Op de oude kaarten op jullie site zijn natuurlijk alleen 'grove schema's' te zien, wat niet op perceelniveau zichtbaar is. Kunnen jullie helpen met archiefmateriaal?<br />
M.vr.gr. Mark Rurup

**Comment by HansNien** [comment]
Verplaatst naar intern (email).
