### ISSUE TITLE
batch Amel-Bevercé

### ISSUE THREAD

**Issue by BavoLens** [Hoogspanningsnet/Netkaart#247]
Alle huidig ingevoerde masten van Amel-Bevercé zijn gesloopt in 2017, kan het uit dienst jaartal op 2017 gezet worden? 
Later zullen we dan de actuele masten invoeren.

**Comment by Netkaart-feedback** [comment]
Done, 65 masten gesloopt in 2017, gelijk de spanning op 0 gezet
