### ISSUE TITLE
beheerdernummer niet zichtbaar

### ISSUE THREAD

**Issue by JohanSwank** [Hoogspanningsnet/Netkaart#250]
Ik ben lijninformatie in BE aan het aanvullen. Wat opvalt, het beheerdernummer is in de webkaart zichtbaar maar in de GE kaart niet. Zie een van de 380kV lijnen in BE.

**Comment by HansNien** [comment]
Ondanks alle interne kanalen, hier ook maar even een reactie. Er mist dan een veldje ergens in een bestand dat de ballon genereert. In versie 7 zal dat wel opgelost zijn.
