### ISSUE TITLE
380 kv <-> 400 kv

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#304]
Naam : Josbert Lonnee<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID=s5131">s5131</a><br><br>Feedback tekst : <br>Vraag: Waar staan de transformatoren die 380 kv en 400 kv naar elkaar transformeren? Op Google Maps zijn ze zowel op Jardelund als Kasso niet te zien staan.

**Comment by HansNien** [comment]
Beste heer Lonnee,

Tussen Kassø en Jardelund bevinden zich geen koppeltrafo's. Het Duitse en Deense koppelnet zijn galvanisch verbonden en worden op dezelfde netspanning bedreven, slechts enige spanningsval daargelaten. Hetzelfde geldt voor de Belgisch/Franse grens of de Zweeds/Noorse grens.

De getallen in de netkaart zijn definitiewaardes. Nederland en Duitsland spreken van 380 kV, maar de meeste andere landen spreken van 400 kV of soms zelfs 420 kV (Noorwegen). Waarom hier lang geleden verschillende definities voor zijn gekozen is een lang verhaal, maar in de praktijk wordt het koppelnet in heel Europa bedreven op dezelfde spanning van meestal tussen 400 en 410 kV, en sommige dagen nog wat hoger. 'Onze' 380 is dus in de praktijk vaak 410.

Als u in de legenda van de netkaart kijkt, ziet u de intervallen conform de NEN-IEC 60038. Alles tussen 365 en 420 kV is in feite gelijk en wordt op 410 uitgenut. Een soortgelijke situatie kan u zien tussen 130 en 132 kV (Denemarken/Zweden) en 220 of 225 kV (Luxemburg/Frankrijk). 

Op de netkaart betekent dit dat twee verschillende definitiespanningen binnen hetzelfde netvlak wel op elkaar kunnen aansluiten, maar twee verschillende netvlakken (kleuren) dus niet, of alleen via een transformator.
