### ISSUE TITLE
Post Stalen 70kV

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#305]
Naam : Niels Mannaerts<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID=v1240">v1240</a><br><br>Feedback tekst : <br>De 70kV post van Stalen bestaat niet meer.<br />
De lijn Stalen - houthalen -> Houthalen - Godsheide (koppeling van de lijn houthalen aan de lijn van godsheide 2<br />
De lijn Stalen - Opglabeek 1 -> Opglabeek - Godsheide (koppeling van de lijn opglabeek 1 aan godsheide 1)<br />
De lijn Opglabeek 2 wordt rechtstreeks gevoed vanuit een transfo 150/70 in stalen.

**Comment by BavoLens** [comment]
Dag Niels,
Bedankt voor de info.
Kan je eventueel een schema geven hoe het dan allemaal aangesloten is? Wat gebeurt er met de 70/10 transfo en de condensatoren 70kv? 

Groeten,

Bavo

**Comment by BavoLens** [comment]
Intussen aangepast
