### ISSUE TITLE
Feedback netkaart m66111 - IW215-32

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#326]
Naam : Mathieu Veys<br>Email : <i>Bekend bij de redactie<i><br>ID : <a href="https://netkaart.hoogspanningsnet.com/balloon3.php?ID=m66111">m66111</a><br><br>Feedback tekst : <br>Geachte<br />
<br />
Omwille van een geschil met het Kadaster waren we benieuwd naar het bouwjaar van mast 32 op de lijn IW215 (en IW214). Dat is de grote hoekmast op het einde van de Elckerlycstraat in Roeselare-Beveren. Op deze site vonden we helaas geen bouwjaar terug.<br />
<br />
We hebben navraag gedaan bij Elia, en die hebben ons per mail bevestigd dat deze mast bouwjaar 1976 heeft. Deze info wilde ik graag met u delen.<br />
<br />
Met vriendelijke groeten,

**Comment by BavoLens** [comment]
We hebben het op de kaart gezet, bedankt !
