### ISSUE TITLE
Spanning < 1000 volt weergeven

### ISSUE THREAD

**Issue by JohanSwank** [Hoogspanningsnet/Netkaart#358]
Spanning weergeven als b.v. 1,5 kV werkt wel in de web kaart maar niet in de GE kaart. In de GE kaart komt dan een pin te staan! Zowel een komma als een punt werkt niet.

**Comment by HansNien** [comment]
Dat is eerder een kwestie van het verversen van het iconenbestand. Een automatische handeling die wel even handmatig op de knop drukken vereist. In de beheerinterface staat in het derde menu linksboven "regenereer het stijlenbestand". Als je daar op drukt na een nieuwe invoer (in de praktijk een icoontje die een combi van spanningen bevat die nog niet eerder is toegepast), dan wordt automatisch een icoon gegenereerd die de gele punaise dan vervangt.

**Comment by JohanSwank** [comment]
Bedankt Hans, ik wist die oplossing wel maar even niet aan gedacht. Gaat het morgen oplossen.

________________________________
Van: HansNien <notifications@github.com>
Verzonden: dinsdag 25 augustus 2020 16:25
Aan: Hoogspanningsnet/Netkaart <Netkaart@noreply.github.com>
CC: JohanSwank <jswank@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Hoogspanningsnet/Netkaart] Spanning < 1000 volt weergeven (#358)


Dat is eerder een kwestie van het verversen van het iconenbestand. Een automatische handeling die wel even handmatig op de knop drukken vereist. In de beheerinterface staat in het derde menu linksboven "regenereer het stijlenbestand". Als je daar op drukt na een nieuwe invoer (in de praktijk een icoontje die een combi van spanningen bevat die nog niet eerder is toegepast), dan wordt automatisch een icoon gegenereerd die de gele punaise dan vervangt.

**Comment by HansNien** [comment]
Uitstekend. (Ik had ook de app even kunnen gebruiken, bedenk ik nu pas.) 
Mooi zo, dan kan dit item worden afgevinkt.
