### ISSUE TITLE
Test van het feedbackformulier

### ISSUE THREAD

**Issue by Netkaart-feedback** [Hoogspanningsnet/Netkaart#48]
Naam : Huis Nienhans<br>Email : nk-hsn <br>ID : <br><br>Feedback tekst : <br>Testbericht via de webkaart na klikken op de algemene link feedback.

**Comment by HansNien** [comment]
Even een functietest gedaan omdat het kan. Dat ziet er goed uit!
Na verzenden formulier verschijnt er netjes een melding.

_Bedankt voor uw feedback we gaan er zo snel mogelijk mee aan de slag.

Feedback geregistreerd op Github!
U kunt de voortgang hier volgen._

Misschien moeten we de tekst daar nog wat van bijschaven naar:

_Bedankt voor uw feedback. We gaan er zo snel mogelijk mee aan de slag.
U kunt de voortgang hier volgen._

Verder buitengewoon netjes. Dit kan wel eens een stuk prettiger gaan werken dan mensen moeizaam te moeten vragen een forumaccount aan te maken.

**Comment by BaDu-HSN** [comment]
Bedankt voor uw feedback, we gaan er zo spoedig mogelijk mee aan de slag

**Comment by BaDu-HSN** [comment]
Issue geregistreerd onder https://github.com/Hoogspanningsnet/Webkaart-scripts/issues/97
