### ISSUE TITLE
iconnew.php stuurt geen cache-control header

### ISSUE THREAD

**Issue by PaulCornelissen** [Hoogspanningsnet/Netkaart#557]
Ik was een beetje aan het kijken naar de werking van de netkaart en het viel me op dat het `iconnew.php` script alle icoontjes serveert, maar geen [cache header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) meestuurt. Als je een beetje rond scrolt op de kaart dan laad je hetzelfde icoontje al snel een paar keer opnieuw (zoals je kunt zien op het screenshot hieronder). Deze icoontjes veranderen in principe niet, dus kunnen prima in een cache lokaal op de computer opgeslagen worden. Dat scheel laadtijd en belasting van de server.

Een goede cache control header zou bijvoorbeeld `Cache-Control: public, max-age=604800, immutable` kunnen zijn. 

![image](https://user-images.githubusercontent.com/5185181/100288244-8fcaa180-2f76-11eb-87d5-9ea63e74c06c.png)

**Comment by BaDu-HSN** [comment]
Hoi Paul,

Dank voor je feedback. Je conclusie is juist.
We zullen deze echter niet fixen, aangezien we binnenkort een nieuwe versie zullen uitrollen waarbij de iconen aan de client-zijde worden gegenereerd.
