### ISSUE TITLE
Situatie EMO110

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Netkaart#65]
Deze kwam binnen via de hoogspanningsmail en in dit motelletje in OK City heb ik nu geen tijd, want over een half uur vangt de jacht weer aan. High risk nu. ;-)

- - - - - - - - - - -

Site	https://www.hoogspanningsnet.com
Naam:	Edwin
Emailadres	
Onderwerp	Netsituatie EMO110
Bericht	Heren, een hele mooie nieuwe kaart app hebben jullie gemaakt. De netsituatie rond EMO110 is veranderd door de komst van het nieuwe station EMZ110

![emo110-en-emz110-netsituatie](https://cloud.githubusercontent.com/assets/23345566/26204791/205c4a8e-3be0-11e7-9ba8-9fbdb0dad714.jpg)

**Comment by BaDu-HSN** [comment]
Ah, dat ziet er uit als een kaartje uit de koker van TenneT
We hebben te maken met een kenner/professional.

**Comment by HansNien** [comment]
Hij heeft het ingestuurd via de email. Wanneer ik een keer tijd heb (nu niet, we zijn nu weer onderweg) zal ik hem een of twee zinnen terugsturen met een kort bedankje, wie weet stuurt hij dan nog eens wat. Dit soort mensen moet je op temperatuur houden.

**Comment by Knarvel** [comment]
Ik pak deze op.
Een bedankje is idd een goed idee, en meteen een leuke kapstok de dialoog gaande te houden. Zo zou je kunnen vragen of in de toekomst de trafo's van EMO op EMZ aangesloten zullen worden. (dan is er mogelijk acuut gevaar voor de lijn EMO-KPN)
