### ISSUE TITLE
Opmerkingen en discussie HoogspanningsNet Netkaart release cycle 6 - captain007

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Netkaart#68]
Via het forum:
http://www.hoogspanningsforum.com/viewtopic.php?p=24048#p24048

De 50kV kabels van Utrecht Lage Weide naar de Jaarbeurs staan ingetekend dwars door het Merwedekanaal. Vandaag viel het me bij een wandeling op de Keulse Kade op dat er langs de stoep soms 50.000 volt bordjes staan, dus ik vermoed dat die kabels dus gewoon onder de stoep liggen langs de Keulse Kade i.p.v. onder het kanaal.

**Comment by HansNien** [comment]
Dank voor de opmerking, inmiddels liggen beide kabels netjes onder de Keulsekade. (Het tracé van de kabel zoals die voorheen op de kaart stond was herleid uit een oud KCD van ENBU uit 2000 of 1999 en een hogere precisie was niet beschikbaar.)
