### ISSUE TITLE
Spanningen windmolens eemshaven

### ISSUE THREAD

**Issue by jeffreykog** [Hoogspanningsnet/Netkaart#75]
Afgelopen weekend vond ik op het internet de opendata van Enexis. Hierop staan alle middenspanning en laagspanningkabels in beheer van Enexis, op een hele grote nauwkeurigheid. Ik was net aan het kijken hoe de situatie in de Eemshaven is en daar zag ik het volgende.

De windmolens aan de borkumkade en aan de westlob hebben allemaal een mooi betonnen Alfen trafokistje ernaast staan. Deze staan allemaal op de Enexis kaart als klantstation, met een 20kV lijn erheen. Ze staan echter op de webkaart als 30kV naar Eemshaven 110. Zie de screenshots.

![Hoogspanningsnet webkaart](https://screenshot.jk-5.nl/ss/2017-07-05_17-01-00/file)

![Enexis kaart](https://screenshot.jk-5.nl/ss/2017-07-05_17-02-43/file)

De vraag is nu waar de informatie dat dit 30kV is wegkomt, want dit lijkt niet waar te zijn.
Zijn de Enexis kaarten hier überhaupt bekend? Of is dit iets om even op het forum te droppen.

**Comment by BaDu-HSN** [comment]
Hoi Jeffrey, mooi speurwerk weer, bedankt daarvoor.
De Enexis opendata is bekend (hadden alle netbeheerders maar zoiets).
Welke info gebruikt is voor de 30kV infield bekabeling is mij onbekend, @HansNien weet jij dat?

**Comment by HansNien** [comment]
@BaDu-HSN en @jk-5: een goede vraag met een goed antwoord. Het getal 30 komt uit een voorlichtingsfilmpje van Essent dat tot op de dag van vandaag op youtroep te vinden is. Tussen 00:50 en 01:05 kan je kabels en spanningen zien.

![windpark westereems kabels](https://user-images.githubusercontent.com/23345566/27925674-f756228c-6285-11e7-8f54-70a15b6b103a.PNG)

Je kan het filmpje zelf ook opzoeken: https://www.youtube.com/watch?v=aYwePXLDSeU

Garantie op correctheid is er niet, maar dit is wel de bron die is gebruikt voor de tracering en de netspanning. Het was ook welgeteld de enige bron met iets van infieldinfo en netspanning die destijds na veel zoekwerk opdook.

Overigens, Jeffrey, hoe heb je die opendata-file van Enexis open gekregen? Ik heb hier een half jaar terug al verschillende dingen geprobeerd, maar zelfs de universiteitscomputers waren niet in staat om ArcGIS zover te krijgen dat ie deze monsterdatasets kon weergeven. Maar de behoefte is aanzienlijk.

**Comment by jeffreykog** [comment]
Aha, interessant. De windmolens westerlijk van de Eemshaven staan niet in de Enexis kaart, dus misschien is dat wat het 30kV gebied is. Disclaimer: ik heb het filmpje nog niet gekeken.

Ik open de data van Enexis in QGis. ArcGis heb ik nog geen ervaring mee. In QGis even een basemap van bijvoorbeeld openstreetmap erin, en dan de zips van Enexis inladen als vector layer (Bovenaan, layer > add layer). Als je de lagen hebt ingeladen kun je bij properties verschillende kleuren en stijlen toepassen gebasseerd op velden zoals voltage en type verbinding.
Het is even sleutelen, maar als het eenmaal werkt krijg je zulke prachtige plaatjes. Als je er verder niet uitkomt vraag gerust, maar ik denk dat dat wel lukt.

![file](https://user-images.githubusercontent.com/1783250/27925920-c8184a12-6286-11e7-9d2d-616e27e01d34.png)

**Comment by HansNien** [comment]
Ach, pfff, dit meen je niet. 
QGis en ermee werken is me vanuit de opleiding goed bekend. Maar omdat we op de universiteit ook ArcGIS hebben (de commerciële moker der GIS-tools) had ik QGis (een net iets kleinere hamer) na de faal maar niet eens meer geprobeerd. Kennelijk had ik dat dus beter toch kunnen doen, want dat screenshot ziet eruit om de vingers bij af te likken.

Dank in elk geval. Momenteel zit ik in het oosten van Drenthe op een ('s avonds) 60 kbit internetlijntje met een 850 MHz 1 GB RAM Win XP-machientje, waarop zelfs deze tool Github alleen als lofi laden wil, dus QGis loopt hier niet. Zodra ik een keer weer op de universiteit ben wordt het meteen geprobeerd. ;-)

**Comment by Knarvel** [comment]
De transformator van Eemshaven-west staat buiten en is goed fotografeerbaar... Wellicht kan iemand met een teleobjektief de typeplaat eens vastleggen.

**Comment by HansNien** [comment]
Inmiddels loopt er een project met implementie van de opendataset. In dat geval zullen we de opendataset als 'waarheid' aanhouden en worden deze molens tot nader order omgezet naar 20 kV. De andere exemplaren zijn waarschijnlijk met netwerk en al in privébeheer en zullen daarom wel niet genoemd staan in de dataset. Omdat de luchtfoto maar één trafo toont (die neem ik aan geen driewikkel 20/30/110 is ;-) ) blijft de vraag an sich nog even open totdat iemand daar veldwerk weet te verrichten, zoals Knarvel al suggereert.

**Comment by jeffreykog** [comment]
Het is al weer een tijdje geleden, maar ik heb eindelijk de logica door achter het verschil tussen de 20kV en 30kV windmolens daar. Het heeft even geduurd.

Kort verhaal: Alle vestas windmolens hebben een alfen trafohuisje, en die staan op de enexis kaart als 20kV klantstation. Alle enercon windmolens komen niet voor op de enexis kaart, en hebben geen trafohuisje. Die zijn dus 30kV.
Dit klopt zelfs met die screenshot uit het filmpje die @HansNien stuurde. Als je goed kijkt zie je dat lang niet alle windmolens in het noordwestelijke deel op die kaart staan. Als je die missende windmolens opzoekt op google maps/streetview zie je dat toevallig die allemaal vestas zijn, en een trafohokje hebben.

Nog een ander puntje, Eemshaven 110kV staat nu als 110/30/20 op de netkaart. Er is wel een enexis transport verdeelstation aanwezig op dat terrein, maar die is niet gekoppeld met de 110/30 trafo. Als dat zo was geweest had hij op de enexis kaart als 'Hoofdstation' gestaan (En was er een tweede trafo aanwezig). Zonde, want ik ben een paar weken voor het begin van deze issue in de eemshaven geweest en ben bij alle tuinen geweest behalve eemshaven 110.

**Comment by HansNien** [comment]
Dank opnieuw voor de uitgebreide toelichting en het onderzoek. Het issue stond/staat inderdaad nog steeds open. Mooi stukje uitzoekwerk en een aannemelijke argumentatie, daar zijn we zeer content mee.

Zoals bekend loopt er een project met de implementatie van de Enexis opendataset. Plan de campagne is om die eerst af te wachten, waarna alle Vestas-machines die op 20 kV werken automatisch correct zijn aangesloten. De Enercons op 30 kV moeten dan handmatig herbekabeld worden aan de hand van luchtfoto's en zo aan te duiden _guesstimation_ van de precieze locatie als ze nog niet op de luchtfoto's staan. Wanneer dat klaar is, krijgt Eemshaven-110 (conform je argumentatie) twee aparte labels, eentje voor de 110/20 kV-trafo en een andere voor de 110/30 kV-trafo. Ook de intekening van het terrein en de tuinen zal iets aangepast worden. 
Uiteraard geldt nog steeds: de eerste de beste van de personen hier die voet aan de grond zet in de Eemshaven bewijst ons een flinke dienst als er wat veldwerk(foto's) van het station mogelijk zijn.

**Comment by HansNien** [comment]
Na veldwerk op 15 februari kan deze dan eindelijk tot nader order dicht.
De trafo draagt bevestigd een typeplaatje met 30 kV erop, maar de windmolens zijn met grote waarschijnlijkheid toch allemaal op 20 kV aangesloten zitten. De 30 kV-trafo lijkt nooit in dienst te zijn gekomen en hij is niet aangesloten. Vermoedelijk dient/diende hij voor toekomstplannen die nooit zijn waargemaakt: het aansluiten van proefmolens die een opspantrafo naar 30 kV hebben. Maar alles lijkt 20 kV in de Eemshaven.

De bestaande kabels kunnen we beter schrappen van de kaart en vervangen door de Enexis opendataset met 20 kV. De molens zelf kloppen dan ook met het vermoeden van JK-5: een Enercon heeft doorgaans de trafo in zijn voet staan, maar de slankere molens van Vestas kunnen dat niet en hebben een separaat trafohuisje nodig.

Zie ter referentie https://www.hoogspanningsforum.com/viewtopic.php?f=12&t=1424

**Comment by jeffreykog** [comment]
Erg interessant veldwerk Hans. Zal dat betekenen dat de enercon machines
zijn aangesloten op dit losse 110/20kV stationnetje omdat deze kabels niet
zichtbaar zijn op de enexis kaart, en dat de vestas machines wel gewoon op
het publieke net van enexis zitten?

Na veldwerk op 15 februari kan deze dan eindelijk tot nader order dicht.

**Comment by HansNien** [comment]
Inmiddels heb ik de situatie op de kaart een beetje lopen verbouwen. Een aantal strengen zijn nu via het inkoopstationnetje aangesloten en naar 20 kV omgekat. Het uiteindelijke beeld zoals het nu op de netkaart staat oogt plausibel en de argumentatie is terug te vinden onder het label van Westereems, nu zijnde 110/20/0 kV. Situatie tot nader order, als we een nieuw stukje informatie tegenkomen kan het misschien toch weer anders zijn.

https://webkaart.hoogspanningsnet.com/index2.php#18/53.44501/6.80708
