### ISSUE TITLE
Locatie station Zuilichem niet correct

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Netkaart#95]
Staat nu op: 51.80138, 5.11707 moet zijn 51.80200, 5.13230.
Deze is ook op de LUFO duidelijk als hoogspanningsstation te herkennen.

Met dank aan DennisB via forum post:
http://www.hoogspanningsforum.com/viewtopic.php?f=13&t=1152&p=24822#p24820

**Comment by Knarvel** [comment]
gekorrigeerd.
